name: Submit Your Struggling Project
description: Share a project you are stuck on so the community can help
title: "[Struggling Project] <project-name>"
labels: ["broken-project"]
body:
  - type: input
    id: repo
    attributes:
      label: Repository URL
      description: Public GitHub repo where your project lives
      placeholder: https://github.com/username/project
    validations:
      required: true

  - type: input
    id: problem
    attributes:
      label: What are you stuck on?
      description: Describe the part you can't fix, error messages, or unexpected behavior
      placeholder: "I keep getting a crash when parsing input…"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Exact steps someone else can follow to see the problem
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What do you want the code to do?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What is happening instead?
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Primary Language
      options:
        - Go
        - Python
        - JavaScript
        - Other
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty
      options:
        - beginner
        - intermediate
        - advanced
    validations:
      required: true
