name: Submit a Broken Project
description: Submit a reproducible broken project for GrindMal
title: "[Broken Project] <project-name>"
labels: ["submission"]
body:
  - type: input
    id: repo
    attributes:
      label: Repository URL
      description: Public GitHub repository containing the broken project
      placeholder: https://github.com/username/project
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Primary Language
      options:
        - Go
        - Python
        - JavaScript
        - Other
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty
      options:
        - easy
        - medium
        - hard
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: Bug Description
      description: What is broken?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Exact steps to trigger the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: The project runs locally
          required: true
        - label: The bug is intentional and reproducible
          required: true
        - label: No solution or hints are included
          required: true
